resolver: lts-18.1

flags: {}
extra-package-dbs: []

packages:
- 'datadog'
- 'dd-wai-middleware'
- 'dd-yesod-middleware'


nix:
  path: ["nixpkgs=https://github.com/NixOS/nixpkgs/tarball/860b56be91fb874d48e23a950815969a7b832fbc"]
  pure: false
  packages: [zlib]
